import Dexie, { type Table } from 'dexie';
import { Trip, TripMember, Household, Expense, Settlement, Activity, PushNotification, User } from '../types';

export class WhoPaidDatabase extends Dexie {
  users!: Table<User, string>;
  trips!: Table<Trip, string>;
  tripMembers!: Table<TripMember, string>;
  households!: Table<Household, string>;
  expenses!: Table<Expense, string>;
  settlements!: Table<Settlement, string>;
  activities!: Table<Activity, string>;
  notifications!: Table<PushNotification, string>;

  constructor() {
    super('WhoPaidDatabase');
    this.version(1).stores({
      users: 'id, email',
      trips: 'id, ownerId, isClosed, isDeleted, updatedAt',
      tripMembers: 'id, tripId, userId, role, isActive',
      households: 'id, tripId',
      expenses: 'id, tripId, paidByUserId, addedByUserId, date, isDeleted, isFlaggedWrong, clientSyncStatus',
      settlements: 'id, tripId, debtorId, creditorId, status',
      activities: 'id, tripId, userId, createdAt',
      notifications: 'id, userId, tripId, isRead, createdAt'
    });
  }
}

export const db = new WhoPaidDatabase();

export const TEST_20_EXPENSES: Expense[] = [
  {
    id: 'exp_1',
    tripId: 'trip_leros_2026',
    description: 'Dinner at Mylos',
    category: 'Food',
    originalAmount: 125,
    originalCurrency: 'EUR',
    convertedAmount: 125,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-12',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_sevket',
    addedByUserId: 'user_sevket',
    payers: [{ userId: 'user_sevket', amount: 125 }],
    participants: [
      { userId: 'user_ozalp', amount: 25 },
      { userId: 'user_betul', amount: 25 },
      { userId: 'user_sevket', amount: 25 },
      { userId: 'user_erhan', amount: 25 },
      { userId: 'user_janna', amount: 25 }
    ],
    splitMode: 'equal',
    date: '2026-08-12T20:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-12T20:35:00.000Z',
    updatedAt: '2026-08-12T20:35:00.000Z'
  },
  {
    id: 'exp_2',
    tripId: 'trip_leros_2026',
    description: 'Airport Taxi',
    category: 'Transport',
    originalAmount: 30,
    originalCurrency: 'EUR',
    convertedAmount: 30,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-12',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 30 }],
    participants: [
      { userId: 'user_ozalp', amount: 6 },
      { userId: 'user_betul', amount: 6 },
      { userId: 'user_sevket', amount: 6 },
      { userId: 'user_erhan', amount: 6 },
      { userId: 'user_janna', amount: 6 }
    ],
    splitMode: 'equal',
    date: '2026-08-12T14:15:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-12T14:20:00.000Z',
    updatedAt: '2026-08-12T14:20:00.000Z'
  },
  {
    id: 'exp_3',
    tripId: 'trip_leros_2026',
    description: 'Boutique Hotel Deposit',
    category: 'Hotel',
    originalAmount: 250,
    originalCurrency: 'EUR',
    convertedAmount: 250,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-13',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [
      { userId: 'user_ozalp', amount: 150 },
      { userId: 'user_erhan', amount: 100 }
    ],
    participants: [
      { userId: 'user_ozalp', amount: 50 },
      { userId: 'user_betul', amount: 50 },
      { userId: 'user_sevket', amount: 50 },
      { userId: 'user_erhan', amount: 50 },
      { userId: 'user_janna', amount: 50 }
    ],
    splitMode: 'equal',
    note: 'Split payment between Ozalp and Erhan',
    date: '2026-08-13T11:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-13T11:05:00.000Z',
    updatedAt: '2026-08-13T11:05:00.000Z'
  },
  {
    id: 'exp_4',
    tripId: 'trip_leros_2026',
    description: 'Bodrum Taverna',
    category: 'Drinks',
    originalAmount: 5000,
    originalCurrency: 'TRY',
    convertedAmount: 104.17,
    mainCurrency: 'EUR',
    exchangeRate: 0.020833,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-14',
    exchangeRateSource: 'Frankfurter ECB (2026-08-14)',
    paidByUserId: 'user_erhan',
    addedByUserId: 'user_erhan',
    payers: [{ userId: 'user_erhan', amount: 5000 }],
    participants: [
      { userId: 'user_ozalp', amount: 1000 },
      { userId: 'user_betul', amount: 1000 },
      { userId: 'user_sevket', amount: 1000 },
      { userId: 'user_erhan', amount: 1000 },
      { userId: 'user_janna', amount: 1000 }
    ],
    splitMode: 'equal',
    date: '2026-08-14T22:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-14T22:05:00.000Z',
    updatedAt: '2026-08-14T22:05:00.000Z'
  },
  {
    id: 'exp_5',
    tripId: 'trip_leros_2026',
    description: 'Castle Tickets',
    category: 'Tickets',
    originalAmount: 40,
    originalCurrency: 'EUR',
    convertedAmount: 40,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-15',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 40 }],
    participants: [
      { userId: 'user_ozalp', amount: 10 },
      { userId: 'user_betul', amount: 10 },
      { userId: 'user_erhan', amount: 10 },
      { userId: 'user_janna', amount: 10 }
    ],
    splitMode: 'equal',
    note: 'Sevket was resting at hotel',
    date: '2026-08-15T15:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-15T15:35:00.000Z',
    updatedAt: '2026-08-15T15:35:00.000Z'
  },
  {
    id: 'exp_6',
    tripId: 'trip_leros_2026',
    description: 'Ferry to Kalymnos',
    category: 'Transport',
    originalAmount: 90,
    originalCurrency: 'EUR',
    convertedAmount: 90,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-13',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_betul',
    addedByUserId: 'user_betul',
    payers: [{ userId: 'user_betul', amount: 90 }],
    participants: [
      { userId: 'user_ozalp', amount: 18 },
      { userId: 'user_betul', amount: 18 },
      { userId: 'user_sevket', amount: 18 },
      { userId: 'user_erhan', amount: 18 },
      { userId: 'user_janna', amount: 18 }
    ],
    splitMode: 'equal',
    date: '2026-08-13T09:15:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-13T09:20:00.000Z',
    updatedAt: '2026-08-13T09:20:00.000Z'
  },
  {
    id: 'exp_7',
    tripId: 'trip_leros_2026',
    description: 'Supermarket Groceries',
    category: 'Food',
    originalAmount: 75,
    originalCurrency: 'EUR',
    convertedAmount: 75,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-13',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_janna',
    addedByUserId: 'user_janna',
    payers: [{ userId: 'user_janna', amount: 75 }],
    participants: [
      { userId: 'user_ozalp', amount: 15 },
      { userId: 'user_betul', amount: 15 },
      { userId: 'user_sevket', amount: 15 },
      { userId: 'user_erhan', amount: 15 },
      { userId: 'user_janna', amount: 15 }
    ],
    splitMode: 'equal',
    date: '2026-08-13T17:40:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-13T17:45:00.000Z',
    updatedAt: '2026-08-13T17:45:00.000Z'
  },
  {
    id: 'exp_8',
    tripId: 'trip_leros_2026',
    description: 'Beach Bar Cocktails',
    category: 'Drinks',
    originalAmount: 55,
    originalCurrency: 'EUR',
    convertedAmount: 55,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-14',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 55 }],
    participants: [
      { userId: 'user_ozalp', amount: 27.50 },
      { userId: 'user_betul', amount: 27.50 }
    ],
    splitMode: 'equal',
    note: 'Ozalp & Betül afternoon drinks',
    date: '2026-08-14T16:20:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-14T16:25:00.000Z',
    updatedAt: '2026-08-14T16:25:00.000Z'
  },
  {
    id: 'exp_9',
    tripId: 'trip_leros_2026',
    description: 'Scooter Rental (2 days)',
    category: 'Transport',
    originalAmount: 90,
    originalCurrency: 'EUR',
    convertedAmount: 90,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-14',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_erhan',
    addedByUserId: 'user_erhan',
    payers: [{ userId: 'user_erhan', amount: 90 }],
    participants: [
      { userId: 'user_erhan', amount: 45 },
      { userId: 'user_janna', amount: 45 }
    ],
    splitMode: 'equal',
    note: 'Erhan and Janna island exploration',
    date: '2026-08-14T10:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-14T10:05:00.000Z',
    updatedAt: '2026-08-14T10:05:00.000Z'
  },
  {
    id: 'exp_10',
    tripId: 'trip_leros_2026',
    description: 'Seafood Lunch at Panteli',
    category: 'Food',
    originalAmount: 160,
    originalCurrency: 'EUR',
    convertedAmount: 160,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-14',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_erhan',
    addedByUserId: 'user_erhan',
    payers: [{ userId: 'user_erhan', amount: 160 }],
    participants: [
      { userId: 'user_ozalp', amount: 32 },
      { userId: 'user_betul', amount: 32 },
      { userId: 'user_sevket', amount: 32 },
      { userId: 'user_erhan', amount: 32 },
      { userId: 'user_janna', amount: 32 }
    ],
    splitMode: 'equal',
    date: '2026-08-14T13:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-14T13:35:00.000Z',
    updatedAt: '2026-08-14T13:35:00.000Z'
  },
  {
    id: 'exp_11',
    tripId: 'trip_leros_2026',
    description: 'Souvenirs & Greek Olive Oil',
    category: 'Other',
    originalAmount: 50,
    originalCurrency: 'USD',
    convertedAmount: 46.00,
    mainCurrency: 'EUR',
    exchangeRate: 0.92,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-15',
    exchangeRateSource: 'Frankfurter ECB (2026-08-15)',
    paidByUserId: 'user_janna',
    addedByUserId: 'user_janna',
    payers: [{ userId: 'user_janna', amount: 50 }],
    participants: [
      { userId: 'user_ozalp', amount: 10 },
      { userId: 'user_betul', amount: 10 },
      { userId: 'user_sevket', amount: 10 },
      { userId: 'user_erhan', amount: 10 },
      { userId: 'user_janna', amount: 10 }
    ],
    splitMode: 'equal',
    date: '2026-08-15T11:20:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-15T11:25:00.000Z',
    updatedAt: '2026-08-15T11:25:00.000Z'
  },
  {
    id: 'exp_12',
    tripId: 'trip_leros_2026',
    description: 'Pharmacy & Sunscreen',
    category: 'Other',
    originalAmount: 25,
    originalCurrency: 'EUR',
    convertedAmount: 25,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-13',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 25 }],
    participants: [
      { userId: 'user_ozalp', amount: 5 },
      { userId: 'user_betul', amount: 5 },
      { userId: 'user_sevket', amount: 5 },
      { userId: 'user_erhan', amount: 5 },
      { userId: 'user_janna', amount: 5 }
    ],
    splitMode: 'equal',
    date: '2026-08-13T12:10:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-13T12:15:00.000Z',
    updatedAt: '2026-08-13T12:15:00.000Z'
  },
  {
    id: 'exp_13',
    tripId: 'trip_leros_2026',
    description: 'Boat Trip to Aspronisi',
    category: 'Tickets',
    originalAmount: 175,
    originalCurrency: 'EUR',
    convertedAmount: 175,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-15',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_erhan',
    addedByUserId: 'user_erhan',
    payers: [
      { userId: 'user_erhan', amount: 95 },
      { userId: 'user_ozalp', amount: 80 }
    ],
    participants: [
      { userId: 'user_ozalp', amount: 35 },
      { userId: 'user_betul', amount: 35 },
      { userId: 'user_sevket', amount: 35 },
      { userId: 'user_erhan', amount: 35 },
      { userId: 'user_janna', amount: 35 }
    ],
    splitMode: 'equal',
    note: 'Co-paid by Erhan & Ozalp',
    date: '2026-08-15T10:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-15T10:05:00.000Z',
    updatedAt: '2026-08-15T10:05:00.000Z'
  },
  {
    id: 'exp_14',
    tripId: 'trip_leros_2026',
    description: 'Windmill Cafe & Desserts',
    category: 'Food',
    originalAmount: 35,
    originalCurrency: 'EUR',
    convertedAmount: 35,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-15',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_betul',
    addedByUserId: 'user_betul',
    payers: [{ userId: 'user_betul', amount: 35 }],
    participants: [
      { userId: 'user_ozalp', amount: 7 },
      { userId: 'user_betul', amount: 7 },
      { userId: 'user_sevket', amount: 7 },
      { userId: 'user_erhan', amount: 7 },
      { userId: 'user_janna', amount: 7 }
    ],
    splitMode: 'equal',
    date: '2026-08-15T18:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-15T18:05:00.000Z',
    updatedAt: '2026-08-15T18:05:00.000Z'
  },
  {
    id: 'exp_15',
    tripId: 'trip_leros_2026',
    description: 'SIM Card Roaming Data',
    category: 'Other',
    originalAmount: 1500,
    originalCurrency: 'TRY',
    convertedAmount: 31.25,
    mainCurrency: 'EUR',
    exchangeRate: 0.020833,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-12',
    exchangeRateSource: 'Frankfurter ECB (2026-08-12)',
    paidByUserId: 'user_sevket',
    addedByUserId: 'user_sevket',
    payers: [{ userId: 'user_sevket', amount: 1500 }],
    participants: [
      { userId: 'user_ozalp', amount: 500 },
      { userId: 'user_sevket', amount: 500 },
      { userId: 'user_erhan', amount: 500 }
    ],
    splitMode: 'equal',
    date: '2026-08-12T16:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-12T16:05:00.000Z',
    updatedAt: '2026-08-12T16:05:00.000Z'
  },
  {
    id: 'exp_16',
    tripId: 'trip_leros_2026',
    description: 'Harbor Parking Fee',
    category: 'Transport',
    originalAmount: 15,
    originalCurrency: 'EUR',
    convertedAmount: 15,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-14',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_janna',
    addedByUserId: 'user_janna',
    payers: [{ userId: 'user_janna', amount: 15 }],
    participants: [
      { userId: 'user_ozalp', amount: 3 },
      { userId: 'user_betul', amount: 3 },
      { userId: 'user_sevket', amount: 3 },
      { userId: 'user_erhan', amount: 3 },
      { userId: 'user_janna', amount: 3 }
    ],
    splitMode: 'equal',
    date: '2026-08-14T23:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-14T23:35:00.000Z',
    updatedAt: '2026-08-14T23:35:00.000Z'
  },
  {
    id: 'exp_17',
    tripId: 'trip_leros_2026',
    description: 'Sunset Wine & Cheese',
    category: 'Drinks',
    originalAmount: 50,
    originalCurrency: 'EUR',
    convertedAmount: 50,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-15',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 50 }],
    participants: [
      { userId: 'user_ozalp', amount: 10 },
      { userId: 'user_betul', amount: 10 },
      { userId: 'user_sevket', amount: 10 },
      { userId: 'user_erhan', amount: 10 },
      { userId: 'user_janna', amount: 10 }
    ],
    splitMode: 'equal',
    date: '2026-08-15T20:15:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-15T20:20:00.000Z',
    updatedAt: '2026-08-15T20:20:00.000Z'
  },
  {
    id: 'exp_18',
    tripId: 'trip_leros_2026',
    description: 'Scuba Diving Session',
    category: 'Tickets',
    originalAmount: 240,
    originalCurrency: 'EUR',
    convertedAmount: 240,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-16',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_sevket',
    addedByUserId: 'user_sevket',
    payers: [{ userId: 'user_sevket', amount: 240 }],
    participants: [
      { userId: 'user_sevket', amount: 80 },
      { userId: 'user_erhan', amount: 80 },
      { userId: 'user_janna', amount: 80 }
    ],
    splitMode: 'equal',
    note: 'Sevket, Erhan, and Janna reef diving',
    date: '2026-08-16T11:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-16T11:05:00.000Z',
    updatedAt: '2026-08-16T11:05:00.000Z'
  },
  {
    id: 'exp_19',
    tripId: 'trip_leros_2026',
    description: 'Bakery Morning Pastries',
    category: 'Food',
    originalAmount: 20,
    originalCurrency: 'EUR',
    convertedAmount: 20,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-16',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_betul',
    addedByUserId: 'user_betul',
    payers: [{ userId: 'user_betul', amount: 20 }],
    participants: [
      { userId: 'user_ozalp', amount: 4 },
      { userId: 'user_betul', amount: 4 },
      { userId: 'user_sevket', amount: 4 },
      { userId: 'user_erhan', amount: 4 },
      { userId: 'user_janna', amount: 4 }
    ],
    splitMode: 'equal',
    date: '2026-08-16T08:45:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-16T08:50:00.000Z',
    updatedAt: '2026-08-16T08:50:00.000Z'
  },
  {
    id: 'exp_20',
    tripId: 'trip_leros_2026',
    description: 'Farewell Dinner at Alinda',
    category: 'Food',
    originalAmount: 225,
    originalCurrency: 'EUR',
    convertedAmount: 225,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-08-16',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 225 }],
    participants: [
      { userId: 'user_ozalp', amount: 45 },
      { userId: 'user_betul', amount: 45 },
      { userId: 'user_sevket', amount: 45 },
      { userId: 'user_erhan', amount: 45 },
      { userId: 'user_janna', amount: 45 }
    ],
    splitMode: 'equal',
    date: '2026-08-16T21:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-08-16T21:05:00.000Z',
    updatedAt: '2026-08-16T21:05:00.000Z'
  }
];

export const CAMINO_20_EXPENSES: Expense[] = [
  {
    id: 'exp_c1',
    tripId: 'trip_camino_2026',
    description: 'Boutique Hotel Iturregi Vineyard Suites (Getaria, 2 Nights)',
    category: 'Hotel',
    originalAmount: 1200,
    originalCurrency: 'EUR',
    convertedAmount: 1200,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-04',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 1200 }],
    participants: [
      { userId: 'user_ozalp', amount: 300 },
      { userId: 'user_sami', amount: 300 },
      { userId: 'user_ali', amount: 300 },
      { userId: 'user_serdar', amount: 300 }
    ],
    splitMode: 'equal',
    date: '2026-09-04T18:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-04T18:05:00.000Z',
    updatedAt: '2026-09-04T18:05:00.000Z'
  },
  {
    id: 'exp_c2',
    tripId: 'trip_camino_2026',
    description: 'Txuleta & Aged Ribeye Feast at Asador Portuetxe (San Sebastian)',
    category: 'Food',
    originalAmount: 480,
    originalCurrency: 'EUR',
    convertedAmount: 480,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-04',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 480 }],
    participants: [
      { userId: 'user_ozalp', amount: 120 },
      { userId: 'user_sami', amount: 120 },
      { userId: 'user_ali', amount: 120 },
      { userId: 'user_serdar', amount: 120 }
    ],
    splitMode: 'equal',
    date: '2026-09-04T21:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-04T21:35:00.000Z',
    updatedAt: '2026-09-04T21:35:00.000Z'
  },
  {
    id: 'exp_c3',
    tripId: 'trip_camino_2026',
    description: 'Michelin Tasting Dinner at Mina (Bilbao River)',
    category: 'Food',
    originalAmount: 640,
    originalCurrency: 'EUR',
    convertedAmount: 640,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-09',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_sami',
    addedByUserId: 'user_sami',
    payers: [{ userId: 'user_sami', amount: 640 }],
    participants: [
      { userId: 'user_ozalp', amount: 160 },
      { userId: 'user_sami', amount: 160 },
      { userId: 'user_ali', amount: 160 },
      { userId: 'user_serdar', amount: 160 }
    ],
    splitMode: 'equal',
    date: '2026-09-09T21:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-09T21:35:00.000Z',
    updatedAt: '2026-09-09T21:35:00.000Z'
  },
  {
    id: 'exp_c4',
    tripId: 'trip_camino_2026',
    description: 'Grilled Whole Turbot & Vintage Wine at Elkano (Getaria)',
    category: 'Food',
    originalAmount: 560,
    originalCurrency: 'EUR',
    convertedAmount: 560,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-06',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ali',
    addedByUserId: 'user_ali',
    payers: [{ userId: 'user_ali', amount: 560 }],
    participants: [
      { userId: 'user_ozalp', amount: 140 },
      { userId: 'user_sami', amount: 140 },
      { userId: 'user_ali', amount: 140 },
      { userId: 'user_serdar', amount: 140 }
    ],
    splitMode: 'equal',
    date: '2026-09-06T14:15:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-06T14:20:00.000Z',
    updatedAt: '2026-09-06T14:20:00.000Z'
  },
  {
    id: 'exp_c5',
    tripId: 'trip_camino_2026',
    description: 'Gran Hotel Domine Bilbao (Guggenheim Views, 2 Nights)',
    category: 'Hotel',
    originalAmount: 830,
    originalCurrency: 'EUR',
    convertedAmount: 830,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-08',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_sami',
    addedByUserId: 'user_sami',
    payers: [{ userId: 'user_sami', amount: 830 }],
    participants: [
      { userId: 'user_ozalp', amount: 207.5 },
      { userId: 'user_sami', amount: 207.5 },
      { userId: 'user_ali', amount: 207.5 },
      { userId: 'user_serdar', amount: 207.5 }
    ],
    splitMode: 'equal',
    date: '2026-09-08T15:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-08T15:05:00.000Z',
    updatedAt: '2026-09-08T15:05:00.000Z'
  },
  {
    id: 'exp_c6',
    tripId: 'trip_camino_2026',
    description: 'Txuleta & Basque Cider Feast at Asador San Martin (Zarautz)',
    category: 'Food',
    originalAmount: 440,
    originalCurrency: 'EUR',
    convertedAmount: 440,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-07',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_serdar',
    addedByUserId: 'user_serdar',
    payers: [{ userId: 'user_serdar', amount: 440 }],
    participants: [
      { userId: 'user_ozalp', amount: 110 },
      { userId: 'user_sami', amount: 110 },
      { userId: 'user_ali', amount: 110 },
      { userId: 'user_serdar', amount: 110 }
    ],
    splitMode: 'equal',
    date: '2026-09-07T21:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-07T21:05:00.000Z',
    updatedAt: '2026-09-07T21:05:00.000Z'
  },
  {
    id: 'exp_c7',
    tripId: 'trip_camino_2026',
    description: 'Parte Vieja Pintxos & Wine Crawl (Gandarias & San Telmo)',
    category: 'Food',
    originalAmount: 320,
    originalCurrency: 'EUR',
    convertedAmount: 320,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-05',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ali',
    addedByUserId: 'user_ali',
    payers: [{ userId: 'user_ali', amount: 320 }],
    participants: [
      { userId: 'user_ozalp', amount: 80 },
      { userId: 'user_sami', amount: 80 },
      { userId: 'user_ali', amount: 80 },
      { userId: 'user_serdar', amount: 80 }
    ],
    splitMode: 'equal',
    date: '2026-09-05T20:45:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-05T20:50:00.000Z',
    updatedAt: '2026-09-05T20:50:00.000Z'
  },
  {
    id: 'exp_c8',
    tripId: 'trip_camino_2026',
    description: 'Txakoli Vineyard Tour & Reserve Tasting at Txomin Etxaniz',
    category: 'Drinks',
    originalAmount: 240,
    originalCurrency: 'EUR',
    convertedAmount: 240,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-05',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_serdar',
    addedByUserId: 'user_serdar',
    payers: [{ userId: 'user_serdar', amount: 240 }],
    participants: [
      { userId: 'user_ozalp', amount: 60 },
      { userId: 'user_sami', amount: 60 },
      { userId: 'user_ali', amount: 60 },
      { userId: 'user_serdar', amount: 60 }
    ],
    splitMode: 'equal',
    date: '2026-09-05T13:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-05T13:35:00.000Z',
    updatedAt: '2026-09-05T13:35:00.000Z'
  },
  {
    id: 'exp_c9',
    tripId: 'trip_camino_2026',
    description: 'Private Coastal Boat Charter at Flysch Geopark (Zumaia)',
    category: 'Tickets',
    originalAmount: 260,
    originalCurrency: 'EUR',
    convertedAmount: 260,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-07',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ali',
    addedByUserId: 'user_ali',
    payers: [{ userId: 'user_ali', amount: 260 }],
    participants: [
      { userId: 'user_ozalp', amount: 65 },
      { userId: 'user_sami', amount: 65 },
      { userId: 'user_ali', amount: 65 },
      { userId: 'user_serdar', amount: 65 }
    ],
    splitMode: 'equal',
    date: '2026-09-07T11:45:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-07T11:50:00.000Z',
    updatedAt: '2026-09-07T11:50:00.000Z'
  },
  {
    id: 'exp_c10',
    tripId: 'trip_camino_2026',
    description: 'Thermal Salt Baths & Thalasso Recovery (Zarautz)',
    category: 'Other',
    originalAmount: 220,
    originalCurrency: 'EUR',
    convertedAmount: 220,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-06',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_serdar',
    addedByUserId: 'user_serdar',
    payers: [{ userId: 'user_serdar', amount: 220 }],
    participants: [
      { userId: 'user_ozalp', amount: 55 },
      { userId: 'user_sami', amount: 55 },
      { userId: 'user_ali', amount: 55 },
      { userId: 'user_serdar', amount: 55 }
    ],
    splitMode: 'equal',
    date: '2026-09-06T16:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-06T16:35:00.000Z',
    updatedAt: '2026-09-06T16:35:00.000Z'
  },
  {
    id: 'exp_c11',
    tripId: 'trip_camino_2026',
    description: 'Surfboard, Wetsuit Rentals & Coaching at Zarautz Beach',
    category: 'Other',
    originalAmount: 180,
    originalCurrency: 'EUR',
    convertedAmount: 180,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-06',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_serdar',
    addedByUserId: 'user_serdar',
    payers: [{ userId: 'user_serdar', amount: 180 }],
    participants: [
      { userId: 'user_ozalp', amount: 45 },
      { userId: 'user_sami', amount: 45 },
      { userId: 'user_ali', amount: 45 },
      { userId: 'user_serdar', amount: 45 }
    ],
    splitMode: 'equal',
    date: '2026-09-06T10:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-06T10:35:00.000Z',
    updatedAt: '2026-09-06T10:35:00.000Z'
  },
  {
    id: 'exp_c12',
    tripId: 'trip_camino_2026',
    description: 'Jacotrans Daily Pilgrim Luggage Transfers (San Sebastian to Bilbao)',
    category: 'Transport',
    originalAmount: 140,
    originalCurrency: 'EUR',
    convertedAmount: 140,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-07',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 140 }],
    participants: [
      { userId: 'user_ozalp', amount: 35 },
      { userId: 'user_sami', amount: 35 },
      { userId: 'user_ali', amount: 35 },
      { userId: 'user_serdar', amount: 35 }
    ],
    splitMode: 'equal',
    date: '2026-09-07T08:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-07T08:05:00.000Z',
    updatedAt: '2026-09-07T08:05:00.000Z'
  },
  {
    id: 'exp_c13',
    tripId: 'trip_camino_2026',
    description: 'Plaza Nueva Pintxos & Basque Gin Tonics (Bilbao Old Town)',
    category: 'Drinks',
    originalAmount: 120,
    originalCurrency: 'EUR',
    convertedAmount: 120,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-08',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ali',
    addedByUserId: 'user_ali',
    payers: [{ userId: 'user_ali', amount: 120 }],
    participants: [
      { userId: 'user_ozalp', amount: 30 },
      { userId: 'user_sami', amount: 30 },
      { userId: 'user_ali', amount: 30 },
      { userId: 'user_serdar', amount: 30 }
    ],
    splitMode: 'equal',
    date: '2026-09-08T23:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-08T23:35:00.000Z',
    updatedAt: '2026-09-08T23:35:00.000Z'
  },
  {
    id: 'exp_c14',
    tripId: 'trip_camino_2026',
    description: 'Guggenheim Museum Bilbao VIP Guided Tickets',
    category: 'Tickets',
    originalAmount: 96,
    originalCurrency: 'EUR',
    convertedAmount: 96,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-08',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 96 }],
    participants: [
      { userId: 'user_ozalp', amount: 24 },
      { userId: 'user_sami', amount: 24 },
      { userId: 'user_ali', amount: 24 },
      { userId: 'user_serdar', amount: 24 }
    ],
    splitMode: 'equal',
    date: '2026-09-08T16:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-08T16:05:00.000Z',
    updatedAt: '2026-09-08T16:05:00.000Z'
  },
  {
    id: 'exp_c15',
    tripId: 'trip_camino_2026',
    description: 'Txepetxa Anchovy & Foie Gras Pintxos Tasting',
    category: 'Food',
    originalAmount: 88,
    originalCurrency: 'EUR',
    convertedAmount: 88,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-05',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_sami',
    addedByUserId: 'user_sami',
    payers: [{ userId: 'user_sami', amount: 88 }],
    participants: [
      { userId: 'user_ozalp', amount: 22 },
      { userId: 'user_sami', amount: 22 },
      { userId: 'user_ali', amount: 22 },
      { userId: 'user_serdar', amount: 22 }
    ],
    splitMode: 'equal',
    date: '2026-09-05T14:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-05T14:35:00.000Z',
    updatedAt: '2026-09-05T14:35:00.000Z'
  },
  {
    id: 'exp_c16',
    tripId: 'trip_camino_2026',
    description: 'Artisanal Idiazabal Cheese, Jamon Iberico & Bread Trail Picnic',
    category: 'Food',
    originalAmount: 84,
    originalCurrency: 'EUR',
    convertedAmount: 84,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-08',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 84 }],
    participants: [
      { userId: 'user_ozalp', amount: 21 },
      { userId: 'user_sami', amount: 21 },
      { userId: 'user_ali', amount: 21 },
      { userId: 'user_serdar', amount: 21 }
    ],
    splitMode: 'equal',
    date: '2026-09-08T12:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-08T12:35:00.000Z',
    updatedAt: '2026-09-08T12:35:00.000Z'
  },
  {
    id: 'exp_c17',
    tripId: 'trip_camino_2026',
    description: 'Coastal Euskotren Train Passes (Zumaia, Zarautz, Deba)',
    category: 'Transport',
    originalAmount: 40,
    originalCurrency: 'EUR',
    convertedAmount: 40,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-07',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ali',
    addedByUserId: 'user_ali',
    payers: [{ userId: 'user_ali', amount: 40 }],
    participants: [
      { userId: 'user_ozalp', amount: 10 },
      { userId: 'user_sami', amount: 10 },
      { userId: 'user_ali', amount: 10 },
      { userId: 'user_serdar', amount: 10 }
    ],
    splitMode: 'equal',
    date: '2026-09-07T09:15:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-07T09:20:00.000Z',
    updatedAt: '2026-09-07T09:20:00.000Z'
  },
  {
    id: 'exp_c18',
    tripId: 'trip_camino_2026',
    description: 'Pilgrim Trailhead Taxis & Shuttles',
    category: 'Transport',
    originalAmount: 50,
    originalCurrency: 'EUR',
    convertedAmount: 50,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-07',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_ozalp',
    addedByUserId: 'user_ozalp',
    payers: [{ userId: 'user_ozalp', amount: 50 }],
    participants: [
      { userId: 'user_ozalp', amount: 12.5 },
      { userId: 'user_sami', amount: 12.5 },
      { userId: 'user_ali', amount: 12.5 },
      { userId: 'user_serdar', amount: 12.5 }
    ],
    splitMode: 'equal',
    date: '2026-09-07T08:45:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-07T08:50:00.000Z',
    updatedAt: '2026-09-07T08:50:00.000Z'
  },
  {
    id: 'exp_c19',
    tripId: 'trip_camino_2026',
    description: 'Morning Specialty Coffee & Fresh Pastel Vasco (Getaria & Deba)',
    category: 'Food',
    originalAmount: 42,
    originalCurrency: 'EUR',
    convertedAmount: 42,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-08',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_sami',
    addedByUserId: 'user_sami',
    payers: [{ userId: 'user_sami', amount: 42 }],
    participants: [
      { userId: 'user_ozalp', amount: 10.5 },
      { userId: 'user_sami', amount: 10.5 },
      { userId: 'user_ali', amount: 10.5 },
      { userId: 'user_serdar', amount: 10.5 }
    ],
    splitMode: 'equal',
    date: '2026-09-08T08:30:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-08T08:35:00.000Z',
    updatedAt: '2026-09-08T08:35:00.000Z'
  },
  {
    id: 'exp_c20',
    tripId: 'trip_camino_2026',
    description: 'Artisanal Txakoli & Bonito del Norte Canned Delicacies',
    category: 'Other',
    originalAmount: 70,
    originalCurrency: 'EUR',
    convertedAmount: 70,
    mainCurrency: 'EUR',
    exchangeRate: 1,
    isManualExchangeRate: false,
    exchangeRateDate: '2026-09-10',
    exchangeRateSource: 'Direct (1:1)',
    paidByUserId: 'user_serdar',
    addedByUserId: 'user_serdar',
    payers: [{ userId: 'user_serdar', amount: 70 }],
    participants: [
      { userId: 'user_ozalp', amount: 17.5 },
      { userId: 'user_sami', amount: 17.5 },
      { userId: 'user_ali', amount: 17.5 },
      { userId: 'user_serdar', amount: 17.5 }
    ],
    splitMode: 'equal',
    date: '2026-09-10T11:00:00.000Z',
    isDeleted: false,
    isFlaggedWrong: false,
    clientSyncStatus: 'synced',
    createdAt: '2026-09-10T11:05:00.000Z',
    updatedAt: '2026-09-10T11:05:00.000Z'
  }
];

// Seed initial mock trips and data (Disabled for clean testing)
export async function seedInitialDataIfNeeded(_force = false) {
  // Auto-seeding disabled for clean production & testing
  return;
}

